version: "3.5"

version: ‘3.5’
networks:
    kong-net:
    driver: bridge
services:
    kong:
        build: ./images/kong/
        container_name: kong_nodb
        networks:
            — kong-net
        environment:
        KONG_DATABASE: “off”
        KONG_DECLARATIVE_CONFIG: kong.yml
        healthcheck:
        test: [“CMD”, “curl”, “-f”, “http://kong:8000”]
        interval: 5s
        timeout: 2s
        retries: 15
        ports:
            — “8000:8000/tcp”
            — “8001:8001/tcp”
            — “8443:8443/tcp”
            — “8444:8444/tcp”