version: "3.5"

services:
    mongo: 
        hostname: mongo
        image: mongo
        ports:
            - 27017:27017
        volumes: 
            - ../init-db:/docker-entrypoint-initdb.d/
        networks:
            - app-medica 

    app:
        hostname: app.medica
        build: 
            dockerfile: Dockerfile
            context: ../Medicament-Back-Spring
        ports:
            - 8080:8080
        environment:
            - SERVER_PORT=8080
            - MONGO_HOST=mongo
        links: 
            - mongo
        depends_on: 
            - mongo
        networks:
            - app-medica 
        restart: unless-stopped

    springrecherche:
        hostname: app.springrecherche
        build: 
            dockerfile: Dockerfile
            context: ../medicament-recherche-elastic
        ports:
            - 8081:8081
        environment:
            - SERVER_PORT=8081
            - MONGO_HOST=mongo
            - ELASTICSEARCH_HOST=elasticsearch
        depends_on: 
            - mongo
            - elasticsearch
        links: 
            - mongo
            - elasticsearch
        networks:
            - app-medica 
        restart: unless-stopped

