version: "3.5"

services:
    app:
        hostname: app.medica.back
        networks:
            - medica-net # on connecte le conteneur "mongo" au réseau "medica-net"
        build: 
            dockerfile: Dockerfile
            context: ../Medicament-Back-Spring
        ports:
            - 8080:8080
        environment:
            - SERVER_PORT=8080
            - MONGO_HOST=mongo
        links: 
            - mongo
        depends_on: 
            - mongo

    app-spring-recherche:
        hostname: app.medica.recherche
        networks:
            - medica-net # on connecte le conteneur "mongo" au réseau "medica-net"
        build: 
            dockerfile: Dockerfile
            context: ../medicament-recherche-elastic
        ports:
            - 8081:8081
        environment:
            - SERVER_PORT=8081
            - MONGO_HOST=mongo
        links: 
            - mongo
        depends_on: 
            - mongo
            - elasticsearch

    # app-ionic:
    #     hostname: com.ionic
    #     ports:
    #         - 8100:8100
  