version: "3.5"

services:
    mongo:
        image: mongo
        ports:
            - 27017:27017

    app:
        hostname: app.medica
        build: 
            dockerfile: Dockerfile
            context: ./Medicament-Back-Spring
        ports:
            - 8080:8080
        environment:
            - SERVER_PORT=8080
            - MONGO_HOST=mongo
        links: 
            - mongo
        depends_on: 
            - mongo

#  app-spring-recherche:
#      hostname: com.recherches
#         ports :
#             - 8081:8081

    # app-ionic:
    #     hostname: com.ionic
    #     ports:
    #         - 8100:8100
  