version: "3.5"

services:
    kong:
        build: ./images/kong/
        networks:
            - app-medica 
        environment:
            KONG_DATABASE: "off"
            KONG_DECLARATIVE_CONFIG: kong.yml
        #healthcheck:
        #test: [“CMD”, “curl”, “-f”, “http://kong:8000”]
        ports:
            - "8000:8000/tcp"
            - "8001:8001/tcp"
            - "8443:8443/tcp"
            - "8444:8444/tcp"